SELECT CATEGORIA, 
       TRIM(TO_CHAR(SUM(SC.VALOR), '$999,999,999')) GRUP_TOTAL,
       TRIM(TO_CHAR(SUM(SUM(SC.VALOR)) over(), '$999,999,999')) TOTAL_GENERAL,
       ROUND(100*(SUM(SC.VALOR) / SUM(SUM(SC.VALOR)) OVER ()),2) PORCENTAJE
  FROM INFO_GASTOS SC
 GROUP BY SC.CATEGORIA;
